### PR TITLE
Fixes for ghc 8.0.1

### PR DESCRIPTION
**Pull request by sergv**

### CODE REVIEW

**Comment by dahlia** [comment]
@pxqr Could you review this?

**Comment by pxqr** [comment]
Hey!

I do not maintain this project anymore. I don't really into how to deal
with it nowadays. Could you tip me at this point?

Thanks!

14 янв 2018 г. 23:12 пользователь "Hong Minhee" <notifications@github.com>
написал:

**Comment by sergv** [comment]
@pxqr Would you mind passing up maintainership over to me then? If you can provide me with access to the repository (or transfer the repo if you don't want to see it again any more) and [add me as a maintainer on hackage](https://wiki.haskell.org/Taking_over_a_package) - than should be enough for me to support the package going forwards.

**Comment by pxqr** [comment]
Ok, will do it soon.

15 янв 2018 г. 11:42 пользователь "Sergey Vinokurov" <
notifications@github.com> написал:

**Comment by dmalikov** [comment]
@pxqr @sergv Any update on this?

**Comment by sergv** [comment]
Nothing from me: the PR's still unmerged out there, the package appears abandoned FWIW.

On 9 July 2018 19:15:15 CEST, Dmitry Malikov <notifications@github.com> wrote:
>@pxqr @sergv Any update on this?
>
>-- 
>You are receiving this because you were mentioned.
>Reply to this email directly or view it on GitHub:
>https://github.com/pxqr/bencoding/pull/7#issuecomment-403552812

-- 
Sent from my Android device with K-9 Mail. Please excuse my brevity.

**Comment by dmalikov** [comment]
@sergv could you please proceed with 'Taking over a package' procedure then?

**Comment by sergv** [comment]
Sure, I'll initiate that this weekend (sorry, cannot start earlier).

On 9 July 2018 21:35:10 CEST, Dmitry Malikov <notifications@github.com> wrote:
>@sergv could you please proceed with 'Taking over a package' procedure
>then?
>
>-- 
>You are receiving this because you were mentioned.
>Reply to this email directly or view it on GitHub:
>https://github.com/pxqr/bencoding/pull/7#issuecomment-403595080

-- 
Sent from my Android device with K-9 Mail. Please excuse my brevity.

**Comment by gwils** [comment]
I've made modifications fixing even more GHC versions here https://github.com/sergv/bencoding/pull/1

**Comment by sergv** [comment]
I've been added as a maintainer and have uploaded new version incorporating all the fixes http://hackage.haskell.org/package/bencoding-0.4.4.0. Please refer to https://github.com/sergv/bencoding to report any issues or submit a PR.

**Pull request closed without merging**
